<script type="text/javascript" src="easyui/jquery.min.js"></script>
<script type="text/javascript" src="easyui/jquery.easyui.min.js"></script>
<script type="text/javascript" src="easyui/easyui-lang-zh_CN.js"></script>
<script type="text/javascript" src="easyui/jquery.slimscroll.min.js"></script>
<script type="text/javascript" src="easyui/datagrid-cellediting.js"></script>
<script type="text/javascript" src="easyui/jquery.edatagrid.js"></script>
<script type="text/javascript" src="easyui/jquery.loadmask.min.js"></script>
<script type="text/javascript" src="easyui/EasyuiUtil.js"></script>
<script type="text/javascript" src="js/jquery.wq.tools.js"></script>
<script type="text/javascript" src="js/lottery.js"></script>


